server.port: 9097
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/nelsonjaimes/nttdata-bc39-proyecto-final
          username: nelsonjaimes
          password: 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
          search-paths: config-server/config-data