name: Build and Publish Docker Image
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with Maven
      run: mvn clean install

    - name: Publish to Docker Hub
      #uses: docker/build-push-action@v1
      uses: isbang/compose-action@v1.4.1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ github.repository }}
        compose-file: "./docker-compose.yml"
        down-flags: "--volumes"
        tag_with_ref: true
        tag_with_sha: true
        tags: ${{ github.sha }}